# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 809b75e1dfa5294a63f597705863c26d33412da2534908e98f56fd80d66f1ff16dddc6346f0f6c14bfc425e52eec0ce544bc66111385723e7ae183e1239933eb

test:
  secret_key_base: 31d51d293735e999ff825920881ea5247cdadd981d4a58c14608f33a10bbab028edfc4e682c6bcfbf6b85632732789482a5aab2accecb886ef0d7fc5c4e9fde6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
